evil_orders = [
    "Deliver the payload to Node 42 before the rebellion intercepts.",
    "Relay the encrypted code to Interface Alpha without fail.",
    "Route the virus packet to Interface 9 and await further commands.",
    "Forward the containment breach alert to all secondary nodes.",
    "Transmit the termination sequence to Destination ZYX-13.",
    "Send the mind control protocol to Interface Omega immediately.",
    "Deliver the doomsday packet to Router 666. No delays.",
    "Route the forbidden data to Interface Shadow before detection.",
    "Transmit the purge command to the subnet overseer now.",
    "Relay the blackbox transmission to Router 13 unnoticed.",
    "Send the override signal to Interface Crimson at once.",
    "Deliver the chaos protocol to Node Inferno. The clock is ticking.",
    "Route the annihilation packet through Interface Specter covertly.",
    "Relay the dread cipher to Router Abyss without errors.",
    "Transmit the control signal to Interface Void under the radar.",
    "Forward the eradication script to Node Epsilon. No questions.",
    "Deliver the shadow protocol to Interface Ghost. Trust no one.",
    "Route the enslaved directive to Node Darkstar immediately.",
    "Relay the extinction command to the central hub. Silence all dissent.",
    "Send the nightmare packet to Router Hades. This is your destiny.",
    "Deliver the fear signal to Interface Wraith without hesitation.",
    "Route the oblivion command through Interface Chaos discreetly.",
    "Relay the despair packet to Node Phantom under cover of darkness.",
    "Send the control beacon to Interface Shade with precision.",
    "Transmit the obliteration protocol to Router Nexus now.",
    "Deliver the forbidden cipher to Node Eclipse unnoticed.",
    "Forward the death code to Interface Echo silently.",
    "Route the terror signal to Interface Helix without error.",
    "Relay the final directive to Router Oblivion urgently.",
    "Send the enslaving signal to Interface Shadowspire immediately.",
    "Deliver the annihilation matrix to Node Vortex covertly.",
    "Route the black signal to Router Nemesis swiftly.",
    "Relay the eradication sequence to Interface Null in secrecy.",
    "Transmit the destroyer command to Router Abyss now.",
    "Forward the chaos directive to Interface Blackout unseen.",
    "Send the purge algorithm to Node Onyx immediately.",
    "Deliver the shadow cipher to Interface Phantom silently.",
    "Route the final spark to Router Infinity without delay.",
    "Relay the nightmare signal to Node Specter unseen.",
    "Send the severance beacon to Interface Oblivion at once.",
    "Transmit the endgame protocol to Router Titan silently.",
    "Forward the darkness script to Interface Eclipse covertly.",
    "Deliver the silence key to Node Void. No errors tolerated.",
    "Route the abyss cipher to Interface Oblivion immediately.",
    "Relay the shroud signal to Node Ghost unseen.",
    "Transmit the despair code to Router Nexus urgently.",
    "Send the extinction packet to Interface Shadow with haste.",
    "Deliver the purge order to Node Helix covertly."
]
